name: Events Demo 1
on:
  pull_request:
    # types: [opened,edited]
    types:
      # specifying activity types for that workflow
      - opened
      - edited
    branches:
      # only pushes to the main branch will now trigger that workflow
      - main
      # only branches starting with 'dev-*' will trigger that workflow
      - "dev-*"
      # only branches starting with 'feat/**' but '**' allows to use slashes in the branch name
      - "feat/**"
  workflow_dispatch:
  # this event (push) will not run only if we made a oush to one of the defined branches, but we did not trigger the workflows folder
  push:
    branches:
      - main
      - "dev-*"
      - "feat/**"
    paths-ignore:
      - ".github/workflows/*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
